### ISSUE TITLE
an option to delete out directory & css files (Improve keepData option.)

### ISSUE THREAD

**Issue by sort72** [n4j1Br4ch1D/postcss-obfuscator#7]
I set `keepData` to false, but it only removed te css-obfuscator directory. It would be nice if that property removes the `out` created directory and the `output.css` file as well. Is it possible?

**Comment by n4j1Br4ch1D** [comment]
hi @sort72  thanks again.
1st `keepData` was designed only for obfuscation data so that's expected.
now I would like to know the reason behind this feature request. (I would assume maybe after the production(obfuscation files) are generated and deployed. Do you want to delete them and keep only development(source files)???). anyway, can you explain the logic behind it?


for now, you can always use the `callBack` option to write your own code that does that.

**Comment by sort72** [comment]
Hi, I was suggesting this because it didn't make sense to me to just remove the generated .json and keep all the obfuscated files, I added the generated files to the .gitignore and it's perfect.
